#!/bin/bash

echo "=== Kubernetes Cluster Security Group Checker ==="
echo ""

# Instance information
echo "Instance Information:"
echo "Master: ec2-51-20-43-244.eu-north-1.compute.amazonaws.com (21.32.12.44)"
echo "Worker-1: ec2-16-170-98-124.eu-north-1.compute.amazonaws.com (21.32.15.122)"
echo "Worker-2: ec2-51-21-255-93.eu-north-1.compute.amazonaws.com"
echo ""

echo "=== AWS Console Steps to Fix Security Groups ==="
echo ""
echo "1. Go to AWS Console > EC2 > Instances"
echo "2. Select your master instance (ec2-51-20-43-244)"
echo "3. Click on the Security Group link"
echo "4. Click 'Edit inbound rules'"
echo "5. Add these rules:"
echo ""
echo "   Rule 1:"
echo "   - Type: All traffic"
echo "   - Protocol: All"
echo "   - Port range: All"
echo "   - Source: Custom"
echo "   - Security group: Select the same security group"
echo ""
echo "   Rule 2 (if Rule 1 doesn't work):"
echo "   - Type: Custom TCP"
echo "   - Protocol: TCP"
echo "   - Port range: 6443"
echo "   - Source: Custom"
echo "   - Security group: Select the same security group"
echo ""
echo "   Rule 3:"
echo "   - Type: Custom TCP"
echo "   - Protocol: TCP"
echo "   - Port range: 10250"
echo "   - Source: Custom"
echo "   - Security group: Select the same security group"
echo ""
echo "6. Click 'Save rules'"
echo "7. Repeat for worker instances if they have different security groups"
echo ""

echo "=== Alternative: Quick Test ==="
echo ""
echo "To quickly test if this fixes the issue, run:"
echo "ssh -i your-key.pem ubuntu@ec2-16-170-98-124.eu-north-1.compute.amazonaws.com 'ping -c 3 21.32.12.44'"
echo ""

echo "=== After fixing security groups, join worker nodes ==="
echo ""
echo "1. Get the join command:"
echo "ssh -i your-key.pem ubuntu@ec2-51-20-43-244.eu-north-1.compute.amazonaws.com 'sudo kubeadm token create --print-join-command'"
echo ""
echo "2. Join worker nodes:"
echo "ssh -i your-key.pem ubuntu@ec2-16-170-98-124.eu-north-1.compute.amazonaws.com 'sudo [JOIN_COMMAND]'"
echo "ssh -i your-key.pem ubuntu@ec2-51-21-255-93.eu-north-1.compute.amazonaws.com 'sudo [JOIN_COMMAND]'"
echo ""
echo "3. Verify cluster:"
echo "ssh -i your-key.pem ubuntu@ec2-51-20-43-244.eu-north-1.compute.amazonaws.com 'kubectl get nodes'" 